"""
VISTA 2.0 — Layer 8: Deployment & Fleet Architecture
Fleet management prototype with device identity, telemetry, OTA, and evidence chain.

Architecture:
  Device Registration → TPM-like Identity → Telemetry Collection
  → OTA Updates → Evidence Chain → Fleet Health Monitoring

Components:
  - DeviceRegistry: TPM-like device identity and registration
  - TelemetryCollector: Device telemetry aggregation
  - OTAUpdateManager: Over-the-air update simulation
  - FleetEvidenceChain: Device-to-cloud evidence chain
  - FleetHealthMonitor: Fleet-wide health monitoring
"""

import hashlib
import json
import time
import uuid
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional, Set, Tuple


# ===================================================================
# Constants
# ===================================================================

MIN_TPM_KEY_LENGTH = 32  # bytes
EVIDENCE_CHAIN_VERSION = "2.0"


# ===================================================================
# Enums
# ===================================================================

class DeviceStatus(Enum):
    ONLINE = "online"
    OFFLINE = "offline"
    UPDATING = "updating"
    ERROR = "error"
    MAINTENANCE = "maintenance"


class TelemetryType(Enum):
    ACCEL_PEAK_G = "accel_peak_g"
    DELTA_V_KMH = "delta_v_kmh"
    CRASH_DETECTED = "crash_detected"
    GPS_LAT = "gps_lat"
    GPS_LON = "gps_lon"
    SPEED_KMH = "speed_kmh"
    BATTERY_PCT = "battery_pct"
    STORAGE_FREE_GB = "storage_free_gb"
    CPU_TEMP_C = "cpu_temp_c"
    UPTIME_S = "uptime_s"
    FW_VERSION = "fw_version"
    LAST_HEARTBEAT = "last_heartbeat"


class OTAPackageStatus(Enum):
    PENDING = "pending"
    DOWNLOADING = "downloading"
    VERIFYING = "verifying"
    INSTALLING = "installing"
    COMPLETE = "complete"
    FAILED = "failed"
    ROLLED_BACK = "rolled_back"


class HealthStatus(Enum):
    HEALTHY = "healthy"
    DEGRADED = "degraded"
    CRITICAL = "critical"
    UNKNOWN = "unknown"


class AlertSeverity(Enum):
    INFO = "info"
    WARNING = "warning"
    ERROR = "error"
    CRITICAL = "critical"


# ===================================================================
# Device Identity (TPM-like)
# ===================================================================

@dataclass
class DeviceIdentity:
    """
    TPM-like device identity with hardware-bound keys.

    In production, this would interface with a TPM 2.0 chip or
    secure element. For simulation, we use deterministic generation
    from a hardware seed.
    """
    device_id: str
    tpm_pubkey: str
    tpm_cert: str
    hardware_serial: str
    manufacturer: str = "VISTA"
    model: str = "VISTA-2.0-HIL"
    firmware_version: str = "2.0.0"
    registration_time: float = 0.0
    last_seen: float = 0.0
    status: DeviceStatus = DeviceStatus.ONLINE

    def to_dict(self) -> Dict[str, Any]:
        return {
            "device_id": self.device_id,
            "tpm_pubkey": self.tpm_pubkey,
            "tpm_cert": self.tpm_cert,
            "hardware_serial": self.hardware_serial,
            "manufacturer": self.manufacturer,
            "model": self.model,
            "firmware_version": self.firmware_version,
            "registration_time": self.registration_time,
            "last_seen": self.last_seen,
            "status": self.status.value,
        }


def generate_tpm_identity(hardware_seed: str) -> DeviceIdentity:
    """
    Generate a TPM-like device identity from a hardware seed.

    In production:
      - hardware_seed comes from TPM芯片 unique serial
      - tpm_pubkey is generated by TPM's RSA/ECC keygen
      - tpm_cert is signed by manufacturer CA

    For simulation:
      - Deterministic generation from seed for reproducibility
    """
    seed_hash = hashlib.sha256(hardware_seed.encode()).hexdigest()

    device_id = f"VISTA-{seed_hash[:12].upper()}"
    tpm_pubkey = f"tpm-pub-{seed_hash[:32]}"
    tpm_cert = f"tpm-cert-{hashlib.sha3_256(hardware_seed.encode()).hexdigest()[:48]}"
    hardware_serial = seed_hash[:16].upper()

    return DeviceIdentity(
        device_id=device_id,
        tpm_pubkey=tpm_pubkey,
        tpm_cert=tpm_cert,
        hardware_serial=hardware_serial,
        registration_time=time.time(),
        last_seen=time.time(),
    )


# ===================================================================
# Telemetry
# ===================================================================

@dataclass
class TelemetryEntry:
    """A single telemetry data point from a device."""
    device_id: str
    telemetry_type: TelemetryType
    value: Any
    timestamp_s: float
    sequence: int = 0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "device_id": self.device_id,
            "telemetry_type": self.telemetry_type.value,
            "value": self.value,
            "timestamp_s": self.timestamp_s,
            "sequence": self.sequence,
        }


@dataclass
class TelemetryAggregate:
    """Aggregated telemetry for a device over a time window."""
    device_id: str
    telemetry_type: TelemetryType
    count: int
    min_value: float
    max_value: float
    mean_value: float
    last_value: float
    window_start_s: float
    window_end_s: float


# ===================================================================
# OTA Update
# ===================================================================

@dataclass
class OTAPackage:
    """An OTA update package."""
    package_id: str
    version: str
    description: str
    checksum_sha256: str
    size_bytes: int
    created_at: float
    target_fw_versions: List[str] = field(default_factory=list)
    metadata: Dict[str, Any] = field(default_factory=dict)


@dataclass
class OTAUpdateRecord:
    """Record of an OTA update attempt on a device."""
    device_id: str
    package_id: str
    status: OTAPackageStatus
    started_at: float
    completed_at: Optional[float] = None
    error_message: Optional[str] = None
    from_version: str = ""
    to_version: str = ""


# ===================================================================
# Fleet Alert
# ===================================================================

@dataclass
class FleetAlert:
    """An alert generated by fleet health monitoring."""
    alert_id: str
    device_id: str
    severity: AlertSeverity
    message: str
    timestamp_s: float
    acknowledged: bool = False
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "alert_id": self.alert_id,
            "device_id": self.device_id,
            "severity": self.severity.value,
            "message": self.message,
            "timestamp_s": self.timestamp_s,
            "acknowledged": self.acknowledged,
        }


# ===================================================================
# Device Registry
# ===================================================================

class DeviceRegistry:
    """
    TPM-like device registration and identity management.

    Handles:
      - Device registration with hardware-bound identity
      - Identity verification via TPM public key
      - Device status tracking
      - Firmware version management

    Security model:
      - Each device has a unique TPM-derived identity
      - Identity is bound to hardware (can't be cloned)
      - Registration requires manufacturer signature (simulated)
    """

    def __init__(self):
        self._devices: Dict[str, DeviceIdentity] = {}
        self._registration_log: List[Dict[str, Any]] = []
        self._tpm_key_index: Dict[str, str] = {}  # pubkey -> device_id

    @property
    def device_count(self) -> int:
        return len(self._devices)

    @property
    def online_count(self) -> int:
        return sum(1 for d in self._devices.values()
                   if d.status == DeviceStatus.ONLINE)

    def register_device(self, hardware_seed: str,
                        manufacturer: str = "VISTA",
                        model: str = "VISTA-2.0-HIL") -> DeviceIdentity:
        """
        Register a new device with TPM-like identity.

        Args:
            hardware_seed: Unique hardware identifier (e.g., TPM serial)
            manufacturer: Device manufacturer
            model: Device model

        Returns:
            DeviceIdentity with generated TPM keys

        Raises:
            ValueError: If device already registered
        """
        identity = generate_tpm_identity(hardware_seed)
        identity.manufacturer = manufacturer
        identity.model = model

        # Check for duplicate
        if identity.device_id in self._devices:
            raise ValueError(f"Device {identity.device_id} already registered")

        # Check TPM key collision
        if identity.tpm_pubkey in self._tpm_key_index:
            raise ValueError("TPM key collision detected")

        self._devices[identity.device_id] = identity
        self._tpm_key_index[identity.tpm_pubkey] = identity.device_id

        self._registration_log.append({
            "action": "register",
            "device_id": identity.device_id,
            "timestamp": time.time(),
            "hardware_serial": identity.hardware_serial,
        })

        return identity

    def get_device(self, device_id: str) -> Optional[DeviceIdentity]:
        """Get device identity by ID."""
        return self._devices.get(device_id)

    def verify_identity(self, device_id: str, tpm_pubkey: str) -> bool:
        """
        Verify a device's TPM public key matches registration.

        In production, this would verify against TPM certificate chain.
        """
        device = self._devices.get(device_id)
        if device is None:
            return False
        return device.tpm_pubkey == tpm_pubkey

    def update_status(self, device_id: str, status: DeviceStatus) -> bool:
        """Update device status."""
        device = self._devices.get(device_id)
        if device is None:
            return False
        device.status = status
        device.last_seen = time.time()
        return True

    def update_firmware(self, device_id: str, version: str) -> bool:
        """Update device firmware version."""
        device = self._devices.get(device_id)
        if device is None:
            return False
        device.firmware_version = version
        device.last_seen = time.time()
        return True

    def heartbeat(self, device_id: str) -> bool:
        """Record a heartbeat from a device."""
        device = self._devices.get(device_id)
        if device is None:
            return False
        device.last_seen = time.time()
        if device.status == DeviceStatus.OFFLINE:
            device.status = DeviceStatus.ONLINE
        return True

    def get_stale_devices(self, timeout_s: float = 300.0) -> List[DeviceIdentity]:
        """Get devices that haven't sent heartbeat within timeout."""
        now = time.time()
        return [d for d in self._devices.values()
                if (now - d.last_seen) > timeout_s]

    def list_devices(self, status: Optional[DeviceStatus] = None) -> List[DeviceIdentity]:
        """List all devices, optionally filtered by status."""
        if status is None:
            return list(self._devices.values())
        return [d for d in self._devices.values() if d.status == status]

    def to_dict(self) -> Dict[str, Any]:
        return {
            "device_count": self.device_count,
            "online_count": self.online_count,
            "devices": {did: d.to_dict() for did, d in self._devices.items()},
            "registration_log": self._registration_log[-100:],  # Last 100
        }


# ===================================================================
# Telemetry Collector
# ===================================================================

class TelemetryCollector:
    """
    Collects and aggregates device telemetry.

    Supports:
      - Multi-device telemetry ingestion
      - Time-windowed aggregation (min, max, mean)
      - Telemetry history for evidence chain
    """

    def __init__(self, aggregation_window_s: float = 60.0):
        self._window_s = aggregation_window_s
        self._telemetry: Dict[str, List[TelemetryEntry]] = {}  # device_id -> entries
        self._sequence_counters: Dict[str, int] = {}

    def ingest(self, device_id: str, telemetry_type: TelemetryType,
               value: Any, timestamp_s: Optional[float] = None) -> TelemetryEntry:
        """
        Ingest a telemetry data point from a device.

        Args:
            device_id: Source device ID
            telemetry_type: Type of telemetry
            value: Telemetry value
            timestamp_s: Timestamp (current time if None)

        Returns:
            TelemetryEntry with assigned sequence number
        """
        if timestamp_s is None:
            timestamp_s = time.time()

        # Auto-increment sequence
        key = f"{device_id}:{telemetry_type.value}"
        seq = self._sequence_counters.get(key, 0)
        self._sequence_counters[key] = seq + 1

        entry = TelemetryEntry(
            device_id=device_id,
            telemetry_type=telemetry_type,
            value=value,
            timestamp_s=timestamp_s,
            sequence=seq,
        )

        if device_id not in self._telemetry:
            self._telemetry[device_id] = []
        self._telemetry[device_id].append(entry)

        return entry

    def get_entries(self, device_id: str,
                    telemetry_type: Optional[TelemetryType] = None,
                    since_s: Optional[float] = None) -> List[TelemetryEntry]:
        """Get telemetry entries for a device."""
        entries = self._telemetry.get(device_id, [])

        if telemetry_type is not None:
            entries = [e for e in entries if e.telemetry_type == telemetry_type]

        if since_s is not None:
            entries = [e for e in entries if e.timestamp_s >= since_s]

        return entries

    def aggregate(self, device_id: str,
                  telemetry_type: TelemetryType,
                  window_s: Optional[float] = None) -> Optional[TelemetryAggregate]:
        """
        Compute aggregated telemetry over a time window.

        Returns:
            TelemetryAggregate with min/max/mean/count
        """
        window = window_s or self._window_s
        now = time.time()
        since = now - window

        entries = self.get_entries(device_id, telemetry_type, since_s=since)
        if not entries:
            return None

        values = [float(e.value) for e in entries if isinstance(e.value, (int, float))]
        if not values:
            return None

        return TelemetryAggregate(
            device_id=device_id,
            telemetry_type=telemetry_type,
            count=len(values),
            min_value=min(values),
            max_value=max(values),
            mean_value=sum(values) / len(values),
            last_value=values[-1],
            window_start_s=since,
            window_end_s=now,
        )

    def get_all_device_ids(self) -> Set[str]:
        """Get all device IDs that have sent telemetry."""
        return set(self._telemetry.keys())

    def get_latest_telemetry(self, device_id: str) -> Dict[TelemetryType, TelemetryEntry]:
        """Get the latest value for each telemetry type from a device."""
        entries = self._telemetry.get(device_id, [])
        latest = {}
        for entry in reversed(entries):
            if entry.telemetry_type not in latest:
                latest[entry.telemetry_type] = entry
        return latest

    def get_total_entries(self) -> int:
        """Get total telemetry entries across all devices."""
        return sum(len(entries) for entries in self._telemetry.values())

    def to_dict(self) -> Dict[str, Any]:
        return {
            "total_entries": self.get_total_entries(),
            "device_count": len(self._telemetry),
            "devices": {
                did: len(entries)
                for did, entries in self._telemetry.items()
            },
        }


# ===================================================================
# OTA Update Manager
# ===================================================================

class OTAUpdateManager:
    """
    Manages over-the-air firmware updates for the fleet.

    Handles:
      - Package creation and distribution
      - Update scheduling and tracking
      - Rollback management
      - Update verification
    """

    def __init__(self):
        self._packages: Dict[str, OTAPackage] = {}
        self._update_records: Dict[str, List[OTAUpdateRecord]] = {}  # device_id -> records
        self._pending_updates: Dict[str, str] = {}  # device_id -> package_id

    def create_package(self, version: str, description: str,
                       firmware_data: bytes,
                       target_fw_versions: Optional[List[str]] = None,
                       metadata: Optional[Dict[str, Any]] = None) -> OTAPackage:
        """
        Create a new OTA update package.

        Args:
            version: Target firmware version
            description: Update description
            firmware_data: Binary firmware payload
            target_fw_versions: Compatible current versions
            metadata: Additional package metadata

        Returns:
            OTAPackage with checksum
        """
        checksum = hashlib.sha256(firmware_data).hexdigest()
        package_id = f"ota-{version}-{checksum[:8]}"

        package = OTAPackage(
            package_id=package_id,
            version=version,
            description=description,
            checksum_sha256=checksum,
            size_bytes=len(firmware_data),
            created_at=time.time(),
            target_fw_versions=target_fw_versions or [],
            metadata=metadata or {},
        )

        self._packages[package_id] = package
        return package

    def schedule_update(self, device_id: str, package_id: str) -> bool:
        """
        Schedule an OTA update for a device.

        Returns True if scheduled, False if package not found.
        """
        if package_id not in self._packages:
            return False

        self._pending_updates[device_id] = package_id

        record = OTAUpdateRecord(
            device_id=device_id,
            package_id=package_id,
            status=OTAPackageStatus.PENDING,
            started_at=time.time(),
        )

        if device_id not in self._update_records:
            self._update_records[device_id] = []
        self._update_records[device_id].append(record)

        return True

    def simulate_update(self, device_id: str, success: bool = True,
                        from_version: str = "2.0.0",
                        to_version: str = "2.1.0") -> OTAUpdateRecord:
        """
        Simulate an OTA update execution (for HIL testing).

        Args:
            device_id: Target device
            success: Whether update succeeds
            from_version: Current firmware version
            to_version: Target firmware version

        Returns:
            OTAUpdateRecord with final status
        """
        records = self._update_records.get(device_id, [])
        if not records:
            # Create a record if none exists
            record = OTAUpdateRecord(
                device_id=device_id,
                package_id="simulated",
                status=OTAPackageStatus.PENDING,
                started_at=time.time(),
                from_version=from_version,
                to_version=to_version,
            )
            records.append(record)
            self._update_records[device_id] = records

        record = records[-1]
        record.from_version = from_version
        record.to_version = to_version

        if success:
            # Simulate progress through states
            record.status = OTAPackageStatus.DOWNLOADING
            record.status = OTAPackageStatus.VERIFYING
            record.status = OTAPackageStatus.INSTALLING
            record.status = OTAPackageStatus.COMPLETE
            record.completed_at = time.time()
        else:
            record.status = OTAPackageStatus.FAILED
            record.error_message = "Simulated update failure"
            record.completed_at = time.time()

        # Clean up pending
        self._pending_updates.pop(device_id, None)

        return record

    def get_update_history(self, device_id: str) -> List[OTAUpdateRecord]:
        """Get update history for a device."""
        return self._update_records.get(device_id, [])

    def get_pending_updates(self) -> Dict[str, str]:
        """Get all pending updates (device_id -> package_id)."""
        return dict(self._pending_updates)

    def get_package(self, package_id: str) -> Optional[OTAPackage]:
        """Get a package by ID."""
        return self._packages.get(package_id)

    def verify_package(self, package_id: str, firmware_data: bytes) -> bool:
        """Verify firmware data matches package checksum."""
        package = self._packages.get(package_id)
        if package is None:
            return False
        actual_checksum = hashlib.sha256(firmware_data).hexdigest()
        return package.checksum_sha256 == actual_checksum

    def to_dict(self) -> Dict[str, Any]:
        return {
            "package_count": len(self._packages),
            "pending_count": len(self._pending_updates),
            "packages": {pid: {
                "version": p.version,
                "size_bytes": p.size_bytes,
                "created_at": p.created_at,
            } for pid, p in self._packages.items()},
            "update_stats": {
                did: len(records)
                for did, records in self._update_records.items()
            },
        }


# ===================================================================
# Fleet Evidence Chain
# ===================================================================

@dataclass
class FleetEvidenceRecord:
    """An evidence record in the fleet-to-cloud chain."""
    record_id: str
    device_id: str
    event_type: str  # "crash", "heartbeat", "telemetry", "ota"
    payload: Dict[str, Any]
    timestamp_s: float
    sha256_hash: str
    sha3_hash: str
    sequence: int
    previous_hash: str  # Chain link

    def to_dict(self) -> Dict[str, Any]:
        return {
            "record_id": self.record_id,
            "device_id": self.device_id,
            "event_type": self.event_type,
            "payload": self.payload,
            "timestamp_s": self.timestamp_s,
            "sha256_hash": self.sha256_hash,
            "sha3_hash": self.sha3_hash,
            "sequence": self.sequence,
            "previous_hash": self.previous_hash,
        }


class FleetEvidenceChain:
    """
    Cryptographic evidence chain from device to cloud.

    Implements a hash-chained ledger where each record's hash includes
    the previous record's hash, making tampering detectable.

    Security properties:
      - Append-only (cannot modify without breaking chain)
      - Dual hashing (SHA-256 + SHA-3) for defense-in-depth
      - Per-device sequence numbers for gap detection
    """

    def __init__(self, shared_secret: bytes = b"fleet-evidence-secret-32b!"):
        if len(shared_secret) < MIN_TPM_KEY_LENGTH:
            raise ValueError(f"Secret must be >= {MIN_TPM_KEY_LENGTH} bytes")
        self._secret = shared_secret
        self._chains: Dict[str, List[FleetEvidenceRecord]] = {}  # device_id -> records
        self._global_sequence = 0

    def _compute_hash(self, data: bytes, algorithm: str = "sha256") -> str:
        """Compute hash."""
        if algorithm == "sha3_256":
            return hashlib.sha3_256(data).hexdigest()
        return hashlib.sha256(data).hexdigest()

    def _compute_hmac(self, data: bytes) -> str:
        """Compute HMAC."""
        return hashlib.pbkdf2_hmac("sha256", self._secret, data, 100000).hex()

    def append_record(self, device_id: str, event_type: str,
                      payload: Dict[str, Any]) -> FleetEvidenceRecord:
        """
        Append a new evidence record to the chain.

        Args:
            device_id: Source device
            event_type: Event type (crash, heartbeat, etc.)
            payload: Evidence payload

        Returns:
            FleetEvidenceRecord with hash chain
        """
        if device_id not in self._chains:
            self._chains[device_id] = []

        chain = self._chains[device_id]
        sequence = len(chain)
        previous_hash = chain[-1].sha256_hash if chain else "0" * 64

        # Build record
        timestamp = time.time()
        record_id = f"fe-{device_id}-{sequence}-{int(timestamp * 1000)}"

        # Serialise for hashing
        record_data = {
            "record_id": record_id,
            "device_id": device_id,
            "event_type": event_type,
            "payload": payload,
            "timestamp_s": timestamp,
            "sequence": sequence,
            "previous_hash": previous_hash,
        }

        data_bytes = json.dumps(record_data, sort_keys=True).encode("utf-8")
        sha256_hash = self._compute_hash(data_bytes, "sha256")
        sha3_hash = self._compute_hash(data_bytes, "sha3_256")

        record = FleetEvidenceRecord(
            record_id=record_id,
            device_id=device_id,
            event_type=event_type,
            payload=payload,
            timestamp_s=timestamp,
            sha256_hash=sha256_hash,
            sha3_hash=sha3_hash,
            sequence=sequence,
            previous_hash=previous_hash,
        )

        chain.append(record)
        self._global_sequence += 1

        return record

    def verify_chain(self, device_id: str) -> Dict[str, Any]:
        """
        Verify the integrity of a device's evidence chain.

        Checks:
          1. Each record's hash matches re-computation
          2. Previous hash links are correct
          3. Sequence numbers are monotonic
          4. Dual hash consistency

        Returns:
            Dict with "valid", "checks", "errors"
        """
        chain = self._chains.get(device_id, [])
        errors = []
        checks = {}

        if not chain:
            return {"valid": True, "checks": {}, "errors": [], "record_count": 0}

        # Check each record
        for i, record in enumerate(chain):
            # Recompute hash
            record_data = {
                "record_id": record.record_id,
                "device_id": record.device_id,
                "event_type": record.event_type,
                "payload": record.payload,
                "timestamp_s": record.timestamp_s,
                "sequence": record.sequence,
                "previous_hash": record.previous_hash,
            }
            data_bytes = json.dumps(record_data, sort_keys=True).encode("utf-8")
            expected_sha256 = self._compute_hash(data_bytes, "sha256")
            expected_sha3 = self._compute_hash(data_bytes, "sha3_256")

            if record.sha256_hash != expected_sha256:
                errors.append(f"Record {i}: SHA-256 mismatch")
                checks[f"record_{i}_sha256"] = False
            else:
                checks[f"record_{i}_sha256"] = True

            if record.sha3_hash != expected_sha3:
                errors.append(f"Record {i}: SHA-3 mismatch")
                checks[f"record_{i}_sha3"] = False
            else:
                checks[f"record_{i}_sha3"] = True

            # Check previous hash link
            if i > 0:
                expected_prev = chain[i - 1].sha256_hash
                if record.previous_hash != expected_prev:
                    errors.append(f"Record {i}: Broken chain link")
                    checks[f"record_{i}_chain"] = False
                else:
                    checks[f"record_{i}_chain"] = True

            # Check sequence
            if record.sequence != i:
                errors.append(f"Record {i}: Sequence mismatch (expected {i}, got {record.sequence})")
                checks[f"record_{i}_sequence"] = False
            else:
                checks[f"record_{i}_sequence"] = True

        valid = len(errors) == 0

        return {
            "valid": valid,
            "checks": checks,
            "errors": errors,
            "record_count": len(chain),
        }

    def get_chain(self, device_id: str) -> List[FleetEvidenceRecord]:
        """Get evidence chain for a device."""
        return list(self._chains.get(device_id, []))

    def get_device_ids(self) -> Set[str]:
        """Get all device IDs with evidence chains."""
        return set(self._chains.keys())

    def get_total_records(self) -> int:
        """Get total records across all devices."""
        return sum(len(chain) for chain in self._chains.values())


# ===================================================================
# Fleet Health Monitor
# ===================================================================

class FleetHealthMonitor:
    """
    Fleet-wide health monitoring and alerting.

    Monitors:
      - Device heartbeat staleness
      - Telemetry anomalies
      - Update status
      - Crash event frequency
      - Storage and battery levels
    """

    def __init__(self,
                 heartbeat_timeout_s: float = 300.0,
                 battery_warning_pct: float = 20.0,
                 storage_warning_gb: float = 5.0,
                 temp_warning_c: float = 70.0):
        self._heartbeat_timeout_s = heartbeat_timeout_s
        self._battery_warning_pct = battery_warning_pct
        self._storage_warning_gb = storage_warning_gb
        self._temp_warning_c = temp_warning_c
        self._alerts: List[FleetAlert] = []
        self._alert_counter = 0

    @property
    def alert_count(self) -> int:
        return len(self._alerts)

    @property
    def unacknowledged_count(self) -> int:
        return sum(1 for a in self._alerts if not a.acknowledged)

    def _create_alert(self, device_id: str, severity: AlertSeverity,
                      message: str, metadata: Optional[Dict] = None) -> FleetAlert:
        """Create and store an alert."""
        self._alert_counter += 1
        alert = FleetAlert(
            alert_id=f"alert-{self._alert_counter:06d}",
            device_id=device_id,
            severity=severity,
            message=message,
            timestamp_s=time.time(),
            metadata=metadata or {},
        )
        self._alerts.append(alert)
        return alert

    def check_heartbeat(self, device: DeviceIdentity) -> Optional[FleetAlert]:
        """Check if a device's heartbeat is stale."""
        age = time.time() - device.last_seen
        if age > self._heartbeat_timeout_s:
            return self._create_alert(
                device.device_id,
                AlertSeverity.WARNING,
                f"Heartbeat stale: {age:.0f}s (timeout: {self._heartbeat_timeout_s}s)",
                {"age_s": age, "timeout_s": self._heartbeat_timeout_s},
            )
        return None

    def check_battery(self, device_id: str,
                      battery_pct: float) -> Optional[FleetAlert]:
        """Check battery level."""
        if battery_pct < self._battery_warning_pct:
            severity = (AlertSeverity.CRITICAL if battery_pct < 10
                       else AlertSeverity.WARNING)
            return self._create_alert(
                device_id, severity,
                f"Low battery: {battery_pct:.1f}%",
                {"battery_pct": battery_pct},
            )
        return None

    def check_storage(self, device_id: str,
                      free_gb: float) -> Optional[FleetAlert]:
        """Check storage level."""
        if free_gb < self._storage_warning_gb:
            severity = (AlertSeverity.CRITICAL if free_gb < 1.0
                       else AlertSeverity.WARNING)
            return self._create_alert(
                device_id, severity,
                f"Low storage: {free_gb:.1f} GB free",
                {"free_gb": free_gb},
            )
        return None

    def check_cpu_temp(self, device_id: str,
                       temp_c: float) -> Optional[FleetAlert]:
        """Check CPU temperature."""
        if temp_c > self._temp_warning_c:
            severity = (AlertSeverity.CRITICAL if temp_c > 85
                       else AlertSeverity.WARNING)
            return self._create_alert(
                device_id, severity,
                f"High CPU temperature: {temp_c:.1f}°C",
                {"temp_c": temp_c},
            )
        return None

    def check_crash_event(self, device_id: str,
                          crash_data: Dict[str, Any]) -> FleetAlert:
        """Generate alert for a crash event."""
        severity = AlertSeverity.INFO
        delta_v = crash_data.get("delta_v_kmh", 0)
        if delta_v > 80:
            severity = AlertSeverity.CRITICAL
        elif delta_v > 40:
            severity = AlertSeverity.WARNING

        return self._create_alert(
            device_id, severity,
            f"Crash event: ΔV={delta_v:.1f} km/h",
            crash_data,
        )

    def check_update_status(self, device_id: str,
                            record: OTAUpdateRecord) -> Optional[FleetAlert]:
        """Check OTA update status."""
        if record.status == OTAPackageStatus.FAILED:
            return self._create_alert(
                device_id, AlertSeverity.ERROR,
                f"OTA update failed: {record.error_message}",
                {"package_id": record.package_id},
            )
        return None

    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert."""
        for alert in self._alerts:
            if alert.alert_id == alert_id:
                alert.acknowledged = True
                return True
        return False

    def get_alerts(self, device_id: Optional[str] = None,
                   severity: Optional[AlertSeverity] = None,
                   unacknowledged_only: bool = False) -> List[FleetAlert]:
        """Get alerts with optional filters."""
        alerts = self._alerts

        if device_id is not None:
            alerts = [a for a in alerts if a.device_id == device_id]

        if severity is not None:
            alerts = [a for a in alerts if a.severity == severity]

        if unacknowledged_only:
            alerts = [a for a in alerts if not a.acknowledged]

        return alerts

    def get_fleet_summary(self) -> Dict[str, Any]:
        """Get fleet-wide health summary."""
        severity_counts = {}
        for alert in self._alerts:
            sev = alert.severity.value
            severity_counts[sev] = severity_counts.get(sev, 0) + 1

        return {
            "total_alerts": self.alert_count,
            "unacknowledged": self.unacknowledged_count,
            "severity_counts": severity_counts,
        }

    def to_dict(self) -> Dict[str, Any]:
        return {
            **self.get_fleet_summary(),
            "alerts": [a.to_dict() for a in self._alerts[-100:]],
        }


# ===================================================================
# Fleet Manager (Top-Level Orchestrator)
# ===================================================================

class FleetManager:
    """
    Top-level fleet management orchestrator.

    Coordinates:
      - DeviceRegistry for identity
      - TelemetryCollector for data
      - OTAUpdateManager for firmware
      - FleetEvidenceChain for integrity
      - FleetHealthMonitor for alerts
    """

    def __init__(self, shared_secret: bytes = b"fleet-evidence-secret-32b!"):
        self.registry = DeviceRegistry()
        self.telemetry = TelemetryCollector()
        self.ota = OTAUpdateManager()
        self.evidence = FleetEvidenceChain(shared_secret)
        self.health = FleetHealthMonitor()

    def register_device(self, hardware_seed: str) -> DeviceIdentity:
        """Register a device and create evidence record."""
        identity = self.registry.register_device(hardware_seed)
        self.evidence.append_record(
            identity.device_id, "registration",
            {"hardware_serial": identity.hardware_serial,
             "model": identity.model}
        )
        return identity

    def process_heartbeat(self, device_id: str,
                          telemetry_data: Optional[Dict[TelemetryType, Any]] = None):
        """Process a device heartbeat with optional telemetry."""
        self.registry.heartbeat(device_id)

        # Record heartbeat evidence
        self.evidence.append_record(device_id, "heartbeat", {})

        # Ingest telemetry if provided
        if telemetry_data:
            for ttype, value in telemetry_data.items():
                self.telemetry.ingest(device_id, ttype, value)

        # Health checks
        device = self.registry.get_device(device_id)
        if device:
            self.health.check_heartbeat(device)

    def record_crash_event(self, device_id: str,
                           crash_data: Dict[str, Any]):
        """Record a crash event from a device."""
        self.evidence.append_record(device_id, "crash", crash_data)
        self.health.check_crash_event(device_id, crash_data)

    def get_fleet_status(self) -> Dict[str, Any]:
        """Get comprehensive fleet status."""
        return {
            "registry": self.registry.to_dict(),
            "telemetry": self.telemetry.to_dict(),
            "ota": self.ota.to_dict(),
            "evidence": {
                "device_count": len(self.evidence.get_device_ids()),
                "total_records": self.evidence.get_total_records(),
            },
            "health": self.health.get_fleet_summary(),
        }


# ===================================================================
# Self-Test
# ===================================================================

def _self_test():
    """Comprehensive self-test of the fleet architecture."""
    print("=" * 70)
    print("DEPLOYMENT & FLEET ARCHITECTURE — SELF-TEST")
    print("=" * 70)

    # --- Test 1: Device Registration ---
    print("\n[TEST 1] Device registration with TPM identity")
    registry = DeviceRegistry()
    dev1 = registry.register_device("hw-seed-alpha-001")
    dev2 = registry.register_device("hw-seed-beta-002")

    print(f"  Device 1: {dev1.device_id}")
    print(f"  Device 2: {dev2.device_id}")
    print(f"  TPM Pubkey 1: {dev1.tpm_pubkey[:32]}...")
    assert registry.device_count == 2
    assert registry.online_count == 2
    print("  PASS: 2 devices registered")

    # --- Test 2: Identity Verification ---
    print("\n[TEST 2] TPM identity verification")
    assert registry.verify_identity(dev1.device_id, dev1.tpm_pubkey)
    assert not registry.verify_identity(dev1.device_id, "fake-key")
    assert not registry.verify_identity("nonexistent", dev1.tpm_pubkey)
    print("  PASS: Identity verification works")

    # --- Test 3: Duplicate Registration ---
    print("\n[TEST 3] Duplicate registration rejected")
    try:
        registry.register_device("hw-seed-alpha-001")
        assert False, "Should have raised ValueError"
    except ValueError:
        print("  PASS: Duplicate correctly rejected")

    # --- Test 4: Device Heartbeat ---
    print("\n[TEST 4] Device heartbeat")
    registry.heartbeat(dev1.device_id)
    device = registry.get_device(dev1.device_id)
    assert device is not None
    print(f"  Last seen: {device.last_seen:.3f}")
    print("  PASS: Heartbeat recorded")

    # --- Test 5: Telemetry Collection ---
    print("\n[TEST 5] Telemetry collection and aggregation")
    collector = TelemetryCollector(aggregation_window_s=60.0)

    # Ingest telemetry
    for i in range(10):
        collector.ingest(
            dev1.device_id,
            TelemetryType.ACCEL_PEAK_G,
            10.0 + i * 5.0,
            timestamp_s=time.time() - (10 - i),
        )
        collector.ingest(
            dev1.device_id,
            TelemetryType.BATTERY_PCT,
            100.0 - i * 5.0,
            timestamp_s=time.time() - (10 - i),
        )

    agg = collector.aggregate(dev1.device_id, TelemetryType.ACCEL_PEAK_G)
    assert agg is not None
    print(f"  Accel: min={agg.min_value:.1f}, max={agg.max_value:.1f}, "
          f"mean={agg.mean_value:.1f}, count={agg.count}")
    assert agg.count == 10
    assert agg.min_value == 10.0
    assert agg.max_value == 55.0
    print("  PASS: Telemetry aggregation correct")

    # --- Test 6: OTA Update ---
    print("\n[TEST 6] OTA update simulation")
    ota = OTAUpdateManager()

    # Create package
    fw_data = b"simulated-firmware-binary-data" * 1000
    pkg = ota.create_package("2.1.0", "Bug fix update", fw_data)
    print(f"  Package: {pkg.package_id}, size={pkg.size_bytes} bytes")

    # Schedule and simulate update
    scheduled = ota.schedule_update(dev1.device_id, pkg.package_id)
    assert scheduled

    record = ota.simulate_update(dev1.device_id, success=True,
                                  from_version="2.0.0", to_version="2.1.0")
    assert record.status == OTAPackageStatus.COMPLETE
    print(f"  Update status: {record.status.value}")

    # Verify package
    verified = ota.verify_package(pkg.package_id, fw_data)
    assert verified
    print("  PASS: OTA update simulated successfully")

    # --- Test 7: Fleet Evidence Chain ---
    print("\n[TEST 7] Fleet evidence chain")
    chain = FleetEvidenceChain(b"fleet-evidence-secret-32b!")

    # Append records
    chain.append_record(dev1.device_id, "registration", {"serial": "A1"})
    chain.append_record(dev1.device_id, "heartbeat", {})
    chain.append_record(dev1.device_id, "crash", {"delta_v_kmh": 45.0})
    chain.append_record(dev2.device_id, "registration", {"serial": "B1"})

    # Verify chain
    result = chain.verify_chain(dev1.device_id)
    print(f"  Device 1 chain: {result['record_count']} records, valid={result['valid']}")
    assert result["valid"]
    assert result["record_count"] == 3

    result2 = chain.verify_chain(dev2.device_id)
    assert result2["valid"]
    assert result2["record_count"] == 1
    print(f"  Total records: {chain.get_total_records()}")
    print("  PASS: Evidence chain verified")

    # --- Test 8: Fleet Health Monitor ---
    print("\n[TEST 8] Fleet health monitoring")
    monitor = FleetHealthMonitor(heartbeat_timeout_s=5.0)

    # Check stale heartbeat
    stale_dev = DeviceIdentity(
        device_id="stale-device", tpm_pubkey="", tpm_cert="",
        hardware_serial="STALE",
        last_seen=time.time() - 100,  # 100 seconds ago
    )
    alert = monitor.check_heartbeat(stale_dev)
    assert alert is not None
    print(f"  Stale heartbeat alert: {alert.severity.value} - {alert.message}")

    # Check low battery
    alert2 = monitor.check_battery("dev-01", 8.5)
    assert alert2 is not None
    print(f"  Low battery alert: {alert2.severity.value}")

    # Check low storage
    alert3 = monitor.check_storage("dev-01", 2.3)
    assert alert3 is not None
    print(f"  Low storage alert: {alert3.severity.value}")

    # Check high temp
    alert4 = monitor.check_cpu_temp("dev-02", 78.5)
    assert alert4 is not None
    print(f"  High temp alert: {alert4.severity.value}")

    # Acknowledge
    monitor.acknowledge_alert(alert.alert_id)
    assert alert.acknowledged
    print(f"  Total alerts: {monitor.alert_count}, unacknowledged: {monitor.unacknowledged_count}")
    print("  PASS: Health monitoring works")

    # --- Test 9: Fleet Manager Integration ---
    print("\n[TEST 9] Fleet manager integration")
    fleet = FleetManager(b"fleet-evidence-secret-32b!")

    # Register devices
    d1 = fleet.register_device("fleet-hw-001")
    d2 = fleet.register_device("fleet-hw-002")
    print(f"  Registered: {d1.device_id}, {d2.device_id}")

    # Process heartbeats with telemetry
    fleet.process_heartbeat(d1.device_id, {
        TelemetryType.BATTERY_PCT: 85.0,
        TelemetryType.SPEED_KMH: 60.0,
    })
    fleet.process_heartbeat(d2.device_id, {
        TelemetryType.BATTERY_PCT: 45.0,
        TelemetryType.CPU_TEMP_C: 65.0,
    })

    # Record crash
    fleet.record_crash_event(d1.device_id, {
        "delta_v_kmh": 42.5,
        "peak_g": 50.0,
        "detected": True,
    })

    # Get fleet status
    status = fleet.get_fleet_status()
    print(f"  Registry: {status['registry']['device_count']} devices")
    print(f"  Telemetry: {status['telemetry']['total_entries']} entries")
    print(f"  Evidence: {status['evidence']['total_records']} records")
    print(f"  Health: {status['health']['total_alerts']} alerts")
    print("  PASS: Fleet manager integration complete")

    # --- Test 10: Evidence Chain Tamper Detection ---
    print("\n[TEST 10] Evidence chain tamper detection")
    tamper_chain = FleetEvidenceChain(b"fleet-evidence-secret-32b!")
    tamper_chain.append_record("tamper-dev", "heartbeat", {"v": 1})
    tamper_chain.append_record("tamper-dev", "heartbeat", {"v": 2})

    # Tamper with record
    records = tamper_chain.get_chain("tamper-dev")
    records[0].payload = {"v": 999}  # Tamper

    result = tamper_chain.verify_chain("tamper-dev")
    print(f"  Valid after tamper: {result['valid']}")
    assert not result["valid"]
    print("  PASS: Tamper detected in evidence chain")

    print(f"\n{'='*70}")
    print("ALL FLEET ARCHITECTURE TESTS PASSED")
    print(f"{'='*70}")


if __name__ == "__main__":
    _self_test()
